services:
  - type: web
    name: mastertech-session
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /
